products:
  - name: "EOP"
    source: "s3"
    artifact_pattern: "Contrast-*.war"
    max_versions: 10

  - name: "Java Agent"
    source: "maven"
    maven_group_id: "com.contrastsecurity"
    maven_artifact_id: "contrast-agent"
    max_versions: 10

  - name: "Flex Agent"
    source: "artifactory"
    artifactory_path: "flex-agent-release"
    artifact_pattern: "contrast-flex-agent*"
    max_versions: 10 

  - name: ".NET Agent"
    source: "artifactory"
    artifactory_path: "dotnet-agent-release"
    artifact_pattern: "ContrastSetup.zip"
    max_versions: 10

  - name: ".NET Agent IIS Installer"
    source: "artifactory"
    artifactory_path: "dotnet-core-installer-release"
    artifact_pattern: "contrast-dotnet-core-agent-for-iis-installer*"
    max_versions: 10

  - name: "Go Agent (Linux AMD64)"
    source: "artifactory"
    artifactory_path: "go-agent-release/linux-amd64"
    artifact_pattern: "contrast-go*"
    max_versions: 10

  - name: "Node Agent"
    source: "artifactory"
    artifactory_path: "node-agent-release"
    artifact_pattern: "node_contrast*"
    max_versions: 10

  - name: "Python Agent"
    source: "artifactory"
    artifactory_path: "python-agent-release"
    artifact_pattern: "contrast-python-agent*"
    max_versions: 10

  - name: "Ruby Agent"
    source: "artifactory"
    artifactory_path: "ruby-agent-release"
    artifact_pattern: "contrast-agent*"
    max_versions: 10

  - name: "Contrast CLI Linux"
    source: "artifactory"
    artifactory_path: "cli/linux"
    artifact_pattern: "contrast*"
    max_versions: 10

  - name: "Contrast CLI Windows"
    source: "artifactory"
    artifactory_path: "cli/windows"
    artifact_pattern: "contrast*"
    max_versions: 10

  - name: "Contrast CLI Mac"
    source: "artifactory"
    artifactory_path: "cli/mac"
    artifact_pattern: "contrast*"
    max_versions: 10
