products:
  - name: "Java Agent"
    direct_download_url: "https://download.java.contrastsecurity.com/latest"
    artifact_pattern: "contrast-agent-*.jar"

  - name: "Flex Agent"
    artifactory_repo: "flex-agent-release"
    artifactory_path: "flex-agent-release"
    artifact_pattern: "contrast-flex-agent*"

  - name: ".NET Agent"
    artifactory_repo: "dotnet-release"
    artifactory_path: "dotnet-release"
    artifact_pattern: "ContrastSetup.zip"

  - name: ".NET Agent IIS Installer"
    artifactory_repo: "dotnet-core-installer-release"
    artifactory_path: "dotnet-core-installer-release"
    artifact_pattern: "contrast-dotnet-core-agent-for-iis-installer*"

  - name: "Go Agent"
    artifactory_repo: "go-agent-release"
    artifactory_path: "go-agent-release"
    artifact_pattern: "contrast-go*"

  - name: "Node Agent"
    artifactory_repo: "node-agent-release"
    artifactory_path: "node-agent-release"
    artifact_pattern: "node_contrast*"

  - name: "Python Agent"
    artifactory_repo: "python-agent-release"
    artifactory_path: "python-agent-release"
    artifact_pattern: "contrast-python-agent*"

  - name: "Ruby Agent"
    artifactory_repo: "ruby-agent-release"
    artifactory_path: "ruby-agent-release"
    artifact_pattern: "contrast-agent*"

  - name: "Contrast CLI Linux"
    artifactory_repo: "cli"
    artifactory_path: "cli"
    artifact_pattern: "contrast*"

  - name: "Contrast CLI Windows"
    artifactory_repo: "cli"
    artifactory_path: "cli"
    artifact_pattern: "contrast*"

  - name: "Contrast CLI Mac"
    artifactory_repo: "cli"
    artifactory_path: "cli"
    artifact_pattern: "contrast*"
