products:
  - name: "EOP"
    source: "s3"
    max_versions: 50
    artifact_pattern: "contrast-eop-(.*)\\.tar\\.gz"
    version_list:  
      - "3.12.10"
      - "3.12.9"
      - "3.12.8"
      - "3.12.7"
      - "3.12.6"
      - "3.12.5"
      - "3.12.4"
      - "3.12.4-PATCH"
      - "3.12.3"
      - "3.12.2"
      - "3.12.1"
      - "3.12.0"
      - "3.11.11"

  - name: "Java Agent"
    source: "maven"
    maven_group_id: "com.contrastsecurity"
    maven_artifact_id: "contrast-agent"
    max_versions: 10

  - name: "Flex Agent"
    source: "artifactory"
    artifactory_path: "flex-agent-release"
    artifact_pattern: "contrast-flex-agent*"
    max_versions: 10 

  - name: ".NET Agent"
    source: "artifactory"
    artifactory_path: "dotnet-agent-release"
    artifact_pattern: "ContrastSetup.zip"
    max_versions: 10

  - name: ".NET Agent IIS Installer"
    source: "artifactory"
    artifactory_path: "dotnet-core-installer-release"
    artifact_pattern: "contrast-dotnet-core-agent-for-iis-installer*"
    max_versions: 10

  - name: "Go Agent (Linux AMD64)"
    source: "artifactory"
    artifactory_path: "go-agent-release"
    platform_subdir: "linux-amd64"
    artifact_pattern: "contrast-go*"
    max_versions: 10

  - name: "Node Agent"
    source: "npm"
    npm_package: "@contrast/agent"
    max_versions: 10

  - name: "Python Agent"
    source: "artifactory"
    artifactory_path: "python-agent-release"
    artifact_pattern: "contrast-python-agent*"
    max_versions: 10

  - name: "Ruby Agent"
    source: "artifactory"
    artifactory_path: "ruby-agent-release"
    artifact_pattern: "contrast-agent*"
    max_versions: 10

  - name: "Contrast CLI Linux"
    source: "artifactory"
    artifactory_path: "cli"
    platform_subdir: "linux"
    artifact_pattern: "contrast*"
    max_versions: 10

  - name: "Contrast CLI Windows"
    source: "artifactory"
    artifactory_path: "cli"
    platform_subdir: "windows"
    artifact_pattern: "contrast*"
    max_versions: 10

  - name: "Contrast CLI Mac"
    source: "artifactory"
    artifactory_path: "cli"
    platform_subdir: "mac"
    artifact_pattern: "contrast*"
    max_versions: 10
