products:
  - name: "EOP"
    s3_bucket_url: "s3://hub-downloads-production/war/"
    s3_public_url: "https://hub-downloads-production.s3.us-east-1.amazonaws.com/war/"
    artifact_pattern: "Contrast-*.war"
    max_versions: 5

  - name: "Java Agent"
    direct_download_url: "https://download.java.contrastsecurity.com/latest"
    artifact_pattern: "contrast-agent-*.jar"

  - name: "Flex Agent"
    artifactory_repo: "flex-agent-release"
    artifactory_path: ""
    artifact_pattern: "contrast-flex-agent*"

  - name: ".NET Agent"
    artifactory_repo: "dotnet-release"
    artifactory_path: ""
    artifact_pattern: "ContrastSetup.zip"

  - name: ".NET Agent IIS Installer"
    artifactory_repo: "dotnet-core-installer-release"
    artifactory_path: ""
    artifact_pattern: "contrast-dotnet-core-agent-for-iis-installer*"

  - name: "Go Agent"
    artifactory_repo: "go-agent-release"
    artifactory_path: "linux-amd64"
    artifact_pattern: "contrast-go*"

  - name: "Node Agent"
    artifactory_repo: "node-agent-release"
    artifactory_path: ""
    artifact_pattern: "node_contrast*"

  - name: "Python Agent"
    artifactory_repo: "python-agent-release"
    artifactory_path: ""
    artifact_pattern: "contrast-python-agent*"

  - name: "Ruby Agent"
    artifactory_repo: "ruby-agent-release"
    artifactory_path: ""
    artifact_pattern: "contrast-agent*"

  - name: "Contrast CLI Linux"
    artifactory_repo: "cli"
    artifactory_path: "linux"
    artifact_pattern: "contrast*"

  - name: "Contrast CLI Windows"
    artifactory_repo: "cli"
    artifactory_path: "windows"
    artifact_pattern: "contrast*"

  - name: "Contrast CLI Mac"
    artifactory_repo: "cli"
    artifactory_path: "mac"
    artifact_pattern: "contrast*"
